/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardTopicsRouteImport } from './routes/_dashboard/topics'
import { Route as DashboardThreadsRouteImport } from './routes/_dashboard/threads'
import { Route as DashboardThreadsThreadIdRouteImport } from './routes/_dashboard/threads.$threadId'

const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTopicsRoute = DashboardTopicsRouteImport.update({
  id: '/topics',
  path: '/topics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardThreadsRoute = DashboardThreadsRouteImport.update({
  id: '/threads',
  path: '/threads',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardThreadsThreadIdRoute =
  DashboardThreadsThreadIdRouteImport.update({
    id: '/$threadId',
    path: '/$threadId',
    getParentRoute: () => DashboardThreadsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/feed': typeof FeedRoute
  '/threads': typeof DashboardThreadsRouteWithChildren
  '/topics': typeof DashboardTopicsRoute
  '/threads/$threadId': typeof DashboardThreadsThreadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/feed': typeof FeedRoute
  '/threads': typeof DashboardThreadsRouteWithChildren
  '/topics': typeof DashboardTopicsRoute
  '/threads/$threadId': typeof DashboardThreadsThreadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboard': typeof DashboardRouteWithChildren
  '/about': typeof AboutRoute
  '/feed': typeof FeedRoute
  '/_dashboard/threads': typeof DashboardThreadsRouteWithChildren
  '/_dashboard/topics': typeof DashboardTopicsRoute
  '/_dashboard/threads/$threadId': typeof DashboardThreadsThreadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/feed'
    | '/threads'
    | '/topics'
    | '/threads/$threadId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/feed' | '/threads' | '/topics' | '/threads/$threadId'
  id:
    | '__root__'
    | '/'
    | '/_dashboard'
    | '/about'
    | '/feed'
    | '/_dashboard/threads'
    | '/_dashboard/topics'
    | '/_dashboard/threads/$threadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  AboutRoute: typeof AboutRoute
  FeedRoute: typeof FeedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/topics': {
      id: '/_dashboard/topics'
      path: '/topics'
      fullPath: '/topics'
      preLoaderRoute: typeof DashboardTopicsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/threads': {
      id: '/_dashboard/threads'
      path: '/threads'
      fullPath: '/threads'
      preLoaderRoute: typeof DashboardThreadsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/threads/$threadId': {
      id: '/_dashboard/threads/$threadId'
      path: '/$threadId'
      fullPath: '/threads/$threadId'
      preLoaderRoute: typeof DashboardThreadsThreadIdRouteImport
      parentRoute: typeof DashboardThreadsRoute
    }
  }
}

interface DashboardThreadsRouteChildren {
  DashboardThreadsThreadIdRoute: typeof DashboardThreadsThreadIdRoute
}

const DashboardThreadsRouteChildren: DashboardThreadsRouteChildren = {
  DashboardThreadsThreadIdRoute: DashboardThreadsThreadIdRoute,
}

const DashboardThreadsRouteWithChildren =
  DashboardThreadsRoute._addFileChildren(DashboardThreadsRouteChildren)

interface DashboardRouteChildren {
  DashboardThreadsRoute: typeof DashboardThreadsRouteWithChildren
  DashboardTopicsRoute: typeof DashboardTopicsRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardThreadsRoute: DashboardThreadsRouteWithChildren,
  DashboardTopicsRoute: DashboardTopicsRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  AboutRoute: AboutRoute,
  FeedRoute: FeedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
